apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/add-base-url: "true"
    ingress.kubernetes.io/base-url-scheme: "/ccp-sock-shop"
    kubernetes.io/ingress.class: nginx
  name: ccp-sock-shop
  namespace: sock-shop
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: front-end
          servicePort: 80
        path: /ccp-sock-shop
